### ISSUE TITLE
Возможность оставлять комментарий при записи на событие

### ISSUE THREAD

**Issue by FoxterBva** [kortirso/comcon#1]
При записи на событий добавить возможность оставлять комментарий, в котором можно указывать дополнительную информацию для создателя события. Например о возможных опозданиях, причинах отсутствия.

В списке подписавшихся можно добавить маркер наличия комментария и отображать его при наведении
![image](https://user-images.githubusercontent.com/8579246/68300122-bef24480-00cf-11ea-97a9-6ca62987fb5e.png)

**Comment by kortirso** [comment]
@FoxterBva Реализовано в 0.7.2
