### ISSUE TITLE
Сортировать рецепты в дропдауне на странице поиска крафтеров

### ISSUE THREAD

**Issue by FoxterBva** [kortirso/comcon#4]
Сортировать рецепты в дропдауне рецептов на странице поиска крафтеров (особенно актуально для наложения чар, тогда они сгруппируются по слоту и будет удобнее искать нужный)

**Comment by kortirso** [comment]
Получается надо сделать сортировку по слоту вещи, для которой этот рецепт?
Сейчас не имеет смысла, т.к. уже готов и на днях будет внедрен более удобный поиск рецептов
