### ISSUE TITLE
Отображать в календаре статус по отношению к событию

### ISSUE THREAD

**Issue by FoxterBva** [kortirso/comcon#8]
Отображать статус участия (подписан/под вопросом/принят/не приду) прямо в сетке календаря и в списке событий справа.
Иконкой или, например, цветом:
без статуса - голубой
подписан - синий
под вопросом - серый
не приду - красный
принят - зеленый

![image](https://user-images.githubusercontent.com/8579246/69047768-871fc100-0a2e-11ea-9464-e5fffe50c725.png)

**Comment by kortirso** [comment]
Статус отображается иконкой
